/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    commodities: Commodity;
    values: Value;
    'process-gates': ProcessGate;
    corridors: Corridor;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    commodities: CommoditiesSelect<false> | CommoditiesSelect<true>;
    values: ValuesSelect<false> | ValuesSelect<true>;
    'process-gates': ProcessGatesSelect<false> | ProcessGatesSelect<true>;
    corridors: CorridorsSelect<false> | CorridorsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'site-copy': SiteCopy;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-copy': SiteCopySelect<false> | SiteCopySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Staff who can sign in to manage the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * All photos used on the public site. Replacing a file here updates the live page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and search.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Cargo dossiers shown on the public site. Add, hide, or reorder at any time.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commodities".
 */
export interface Commodity {
  id: number;
  name: string;
  /**
   * URL path, e.g. avocado → /commodities/avocado
   */
  slug: string;
  tagline: string;
  /**
   * Short origin line shown on the cargo wall, e.g. Nigeria · Kenya
   */
  originFocus: string;
  image: number | Media;
  body: string;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show on the homepage cargo wall.
   */
  featured?: boolean | null;
  order: number;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Company values shown on Home and About.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values".
 */
export interface Value {
  id: number;
  title: string;
  body: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The eight trade gates visitors scroll through. Reorder by number.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-gates".
 */
export interface ProcessGate {
  id: number;
  label: string;
  body: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Origins, the Dubai hub, and destination markets on the manifest strip.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corridors".
 */
export interface Corridor {
  id: number;
  name: string;
  role: 'origin' | 'hub' | 'destination';
  region?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trade enquiries submitted from the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  company: string;
  contactName: string;
  email: string;
  phone?: string | null;
  commodityInterest: string;
  originPreference?: string | null;
  volume?: string | null;
  destination?: string | null;
  message: string;
  status?: ('new' | 'in-progress' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'commodities';
        value: number | Commodity;
      } | null)
    | ({
        relationTo: 'values';
        value: number | Value;
      } | null)
    | ({
        relationTo: 'process-gates';
        value: number | ProcessGate;
      } | null)
    | ({
        relationTo: 'corridors';
        value: number | Corridor;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commodities_select".
 */
export interface CommoditiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  originFocus?: T;
  image?: T;
  body?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "values_select".
 */
export interface ValuesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-gates_select".
 */
export interface ProcessGatesSelect<T extends boolean = true> {
  label?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corridors_select".
 */
export interface CorridorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  region?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  company?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  commodityInterest?: T;
  originPreference?: T;
  volume?: T;
  destination?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Company identity, contact details, and logos. Changes appear across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  legalName: string;
  shortName: string;
  tagline: string;
  heroLine: string;
  /**
   * Optional. Leave empty to use the built-in Concept 1 mark.
   */
  logo?: (number | null) | Media;
  phone: string;
  email: string;
  website?: string | null;
  address: string;
  /**
   * Full Instagram URL. Shown in the top bar and footer.
   */
  instagram?: string | null;
  /**
   * Full Facebook URL. Shown in the top bar and footer.
   */
  facebook?: string | null;
  /**
   * Full Twitter / X URL. Shown in the top bar and footer.
   */
  twitter?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * All public page text. Edit here — no code required.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-copy".
 */
export interface SiteCopy {
  id: number;
  homeKicker?: string | null;
  homeIntro?: string | null;
  homeCta?: string | null;
  /**
   * Small gold label above the cargo heading.
   */
  cargoKicker?: string | null;
  cargoHeading?: string | null;
  cargoIntro?: string | null;
  /**
   * Left side of the homepage corridor — origin / farm.
   */
  heroOriginImage?: (number | null) | Media;
  /**
   * Right side of the homepage corridor — Dubai / trade hub.
   */
  heroHubImage?: (number | null) | Media;
  /**
   * Extra origin photos. The main origin image plus these fade in and out.
   */
  heroOriginGallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Extra Dubai / hub photos. The main hub image plus these fade in and out.
   */
  heroHubGallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  aboutKicker?: string | null;
  aboutHeading?: string | null;
  aboutBody?: string | null;
  aboutImage?: (number | null) | Media;
  workKicker?: string | null;
  workIntro?: string | null;
  sourcingTitle?: string | null;
  sourcingBody?: string | null;
  exportTitle?: string | null;
  exportBody?: string | null;
  sourcingImage?: (number | null) | Media;
  exportImage?: (number | null) | Media;
  processKicker?: string | null;
  processIntro?: string | null;
  reasons?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  contactKicker?: string | null;
  contactHeading?: string | null;
  contactBody?: string | null;
  privacyBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  legalName?: T;
  shortName?: T;
  tagline?: T;
  heroLine?: T;
  logo?: T;
  phone?: T;
  email?: T;
  website?: T;
  address?: T;
  instagram?: T;
  facebook?: T;
  twitter?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-copy_select".
 */
export interface SiteCopySelect<T extends boolean = true> {
  homeKicker?: T;
  homeIntro?: T;
  homeCta?: T;
  cargoKicker?: T;
  cargoHeading?: T;
  cargoIntro?: T;
  heroOriginImage?: T;
  heroHubImage?: T;
  heroOriginGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  heroHubGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  aboutKicker?: T;
  aboutHeading?: T;
  aboutBody?: T;
  aboutImage?: T;
  workKicker?: T;
  workIntro?: T;
  sourcingTitle?: T;
  sourcingBody?: T;
  exportTitle?: T;
  exportBody?: T;
  sourcingImage?: T;
  exportImage?: T;
  processKicker?: T;
  processIntro?: T;
  reasons?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  contactKicker?: T;
  contactHeading?: T;
  contactBody?: T;
  privacyBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}